---
- name: Creating Grafana Dashboard Dir
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: 0775
 
- name: Grafana - dasboard Provisioning file
  copy:
    src: dashboardConfig.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboardConfig.yaml
    owner: grafana
    group: grafana
    mode: 0640

- name: Grafana - copy DATASOURCE YAML 
  copy:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
    owner: grafana
    group: grafana
    mode: 0640
  notify: reload-grafana

- name: Grafana - copy Global MySql dashbord JSON file 
  copy:
    src: dashboard.json
    dest: /var/lib/grafana/dashboards/dashboard.json
    owner: grafana
    group: grafana
    mode: 0640
  notify: reload-grafana
